name: CI/CD

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:

  lint:
    name: Lint ${{ matrix.environment }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment:
        - staging

    defaults:
      run:
        shell: bash
        working-directory: environments/${{ matrix.environment }}

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.6

    - name: Terraform Format
      run: terraform fmt -check

  deploy-staging:
    name: Deploy staging
    needs: lint
    uses: ./.github/workflows/deploy-terraform.yml
    with:
      environment: staging
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

  deploy-production:
    name: Deploy production
    needs: deploy-staging
    uses: ./.github/workflows/deploy-terraform.yml
    with:
      environment: production
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
